// The live examples run the package's own web engine, not a lookalike. Its
// DOM renderer (everything in ../web except the React Native <View> wrapper)
// is copied in here, so the site stays self-contained for the Workers build
// and can never drift from what ships.
import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";

const source = new URL("../../web/", import.meta.url).pathname;
const out = new URL("../src/lib/numeric-text/engine/", import.meta.url).pathname;

// NumericTextView.tsx and the index files pull in react-native; the site has its own wrapper.
const FOLDERS = ["animation", "enums", "glyphs", "records"];
const FILES = ["views/NumericTextLabel.ts"];

const HEADER = "// Generated by scripts/sync-engine.mjs from web/ in the package. Do not edit.\n";

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });

for (const folder of FOLDERS) await cp(join(source, folder), join(out, folder), { recursive: true });
for (const file of FILES) {
	await mkdir(dirname(join(out, file)), { recursive: true });
	await cp(join(source, file), join(out, file));
}

const files = (await readdir(out, { recursive: true })).filter((file) => file.endsWith(".ts"));
for (const file of files) {
	const path = join(out, file);
	await writeFile(path, HEADER + (await readFile(path, "utf8")));
}

console.log(`Synced ${files.length} engine files into ${relative(process.cwd(), out).split(sep).join("/")}`);
